import type {Metadata} from "next";
import {Inter} from 'next/font/google';
import "./globals.css";
import {Providers} from "./_components/Providers";
import favicon from "@/app/_assets/favicon.ico";
import Header from "./_components/Header"; // Подключаем Header
import Footer from "./_components/Footer"; // Подключаем Footer
import FadeWrapper from "@/app/_components/FadeWrapper";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: favicon.src
    }
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.variable} antialiased`}>
        <Providers>
            <FadeWrapper>
          <div className="flex flex-col min-h-svh">
            <Header/>
            <main className="flex-grow container mx-auto px-3">
                {children}
            </main>
            <Footer />
          </div>
                </FadeWrapper>
        </Providers>
        </body>
        </html>
);
}
